# Generated by Django 2.2.6 on 2019-11-04 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='audio/beats', validators=[django.core.validators.FileExtensionValidator(['wav'])])),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bpm', models.PositiveSmallIntegerField(choices=[(65, 'Slow'), (85, 'Mid'), (120, 'Fast')], validators=[django.core.validators.MinValueValidator(65), django.core.validators.MaxValueValidator(140)])),
            ],
        ),
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bpm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recording', models.FileField(upload_to='audio/raps')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Beat')),
            ],
        ),
    ]
