# Generated by Django 2.2.6 on 2019-11-06 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='bpm',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(65), django.core.validators.MaxValueValidator(140)]),
        ),
    ]
