# Generated by Django 2.2.6 on 2019-11-06 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191106_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='file',
            field=models.FileField(upload_to='audio/beats', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3'])]),
        ),
    ]
